/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import javafx.application.Application;

public class Main {

    public static void main(String[] args) {
        try {
            DataBaseConnection instance = DataBaseConnection.getInstance();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        BackgroundMusic backgroundMusic = new BackgroundMusic();
        new Thread(backgroundMusic).start();
        Application.launch(App.class, args);
    }
}
